// Generated by scripts/codingplan/platform_pages/generate.js
(function(root){
  const pages = {
  "command-code": {
    "title": "Command Code",
    "url": "/platforms/command-code/"
  },
  "minimax": {
    "title": "MiniMax Token Plan",
    "url": "/platforms/minimax/"
  },
  "opencode": {
    "title": "OpenCode Go",
    "url": "/platforms/opencode/"
  },
  "zhipu": {
    "title": "智谱 GLM Coding Plan",
    "url": "/platforms/zhipu/"
  }
};
  const api = { pages, getUrl: slug => Object.prototype.hasOwnProperty.call(pages, slug) ? pages[slug].url : null };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.PlatformPages = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
